Repository openshift/elasticsearch-operator, pull requests merged in 2018-12, with the labels that each got.

#41 construct kubeconfig from sa secret and downward api
  hack/test-e2e.sh
  manifests/02-role.yaml
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/S

#33 Operator can add and remove ES nodes
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/render_config.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  pkg/utils/exec.go
  pkg/utils/exec_util.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, lgtm, size/XL

#44 Updating services to publish not ready and updating readiness probe
  pkg/k8shandler/services.go
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/S

#45 fix unexported env. vars. and remote registry integration
  Makefile
  README.md
  hack/common
  hack/deploy-image.sh
  hack/deploy.sh
Labels: approved, lgtm, size/M

#43 Log250 rolling restart
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/utils/exec_util.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#48 fix 1655675. Deployment progress deadline
  pkg/k8shandler/deployment.go
Labels: approved, lgtm, size/XS

#47 Setting deployment as Paused: true initially and flipping it as part …
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/M

#49 port forwarding can take a while to come up
  hack/deploy-image.sh
Labels: approved, lgtm, size/S
