Repository openshift/elasticsearch-operator, pull requests merged in 2018-10, with the labels that each got.

#13 [issue #9] changed elasticsearch certificates mount point
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/XS

#14 clean up a bit
  pkg/stub/handler.go
Labels: approved, lgtm, size/XS

#17 remove origin- prefix
  deploy/cr.yaml
  deploy/deployment.yaml
  deploy/examples/onenode-emptydir-es.yaml
  deploy/examples/onenode-hostmounted-es.yaml
  deploy/examples/onenode-pvc-es.yaml
  deploy/openshift/elasticsearch-template.yaml
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/S

#16 oauth proxy support was never really implemented
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/render_config.go
  tests/test-secure-cdm.sh
Labels: approved, lgtm, size/L

#18 [log203] Source ES cluster configuration from CR
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/render_config.go
Labels: approved, lgtm, size/L

#23 remove PROMETHEUS_USER var
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, release/4.0
