Repository openshift/elasticsearch-operator, pull requests merged in 2018-11, with the labels that each got.

#19 [log202] Provide status info about elasticsearch cluster
  Gopkg.lock
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/exec.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  pkg/stub/handler.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/priority_test.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/spdy_test.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/spdy_bench_test.go
  vendor/github.com/docker/spdystream/spdy_test.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/github.com/docker/spdystream/ws/connection.go
  vendor/github.com/docker/spdystream/ws/ws_test.go
Labels: approved, lgtm, size/XXL

#25 [log215] adding service monitor object
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/services.go
  pkg/k8shandler/util.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#26 Updating ES status to include pod status map
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/L

#27 e2e test cleanup
  Dockerfile
  README.md
  deploy/role.yaml
  pkg/k8shandler/statefulset.go
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/M

#30 fix RULES_FILE_PATH
  Dockerfile.rhel7
  hack/cr.yaml
Labels: approved, lgtm, release/4.0

#35 Update manifest files
  README.md
  manifests/01-service-account.yaml
  manifests/02-role.yaml
  manifests/03-role-bindings.yaml
  manifests/04-crd.yaml
  manifests/05-deployment.yaml
Labels: approved, lgtm, size/S

#34 Remove ability to configure sa, secret, configmap names in CR
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/serviceaccount.go
Labels: approved, lgtm, size/S

#37 Adding label for openshift-tuned operator es profile
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/XS

#36 Enable log level and format selection
  cmd/elasticsearch-operator/main.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/services.go
  pkg/stub/handler.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#39 dynamically construct log level list from logrus
  cmd/elasticsearch-operator/main.go
Labels: approved, lgtm, size/M

#38 Managed spec
  Makefile
  README.md
  hack/cr.yaml
  hack/test-e2e.sh
  manifests/01-service-account.yaml
  manifests/02-role.yaml
  manifests/03-role-bindings.yaml
  manifests/04-crd.yaml
  manifests/05-deployment.yaml
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/util.go
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/L

#40 more cleanup - better integration with cluster-logging-operator
  Makefile
  deploy/examples/onenode-emptydir-es.yaml
  deploy/examples/onenode-hostmounted-es.yaml
  deploy/examples/onenode-pvc-es.yaml
  deploy/openshift/elasticsearch-template.yaml
  deploy/operator.yaml
  hack/common
  hack/deploy-setup.sh
  hack/deploy.sh
  manifests/05-deployment.yaml
  pkg/stub/handler.go
Labels: approved, lgtm, size/M
