Repository openshift/elasticsearch-operator, pull requests merged in 2019-04, with the labels that each got.

#114 Bug 1694097 - Check if nodeselectors have changed
  pkg/apis/elasticsearch/v1/types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, lgtm, size/L

#115 Fix 1662273 - cant find es metrics
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
Labels: approved, lgtm, size/S

#116 Bug 1686173 - Correctly evaluate case where node previously existed
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, lgtm, size/XS

#121 Bringing over recent changes from master to master-post-release
  pkg/apis/elasticsearch/v1/types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, lgtm, size/L

#119 UBI support; allow image build and push with oal logging
  Makefile
  README.md
  hack/build-image.sh
  hack/common
  hack/deploy-image.sh
Labels: approved, lgtm, size/L

#124 fixing watermark status checks
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/S

#125 the repo for use with UBI has moved
  README.md
  hack/common
Labels: approved, lgtm, size/S

#126 merge master into master-post-release
  Makefile
  README.md
  hack/build-image.sh
  hack/common
  hack/deploy-image.sh
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/L

#120 Enable the operator to perform unassisted updates
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/L
