Repository openshift/elasticsearch-operator, pull requests merged in 2019-03, with the labels that each got.

#76 Secure metrics endpoint with oauth-proxy
  files/prometheus_alerts.yml
  hack/cr.yaml
  hack/deploy-setup.sh
  hack/prometheus-rules.yaml
  hack/test-e2e.sh
  manifests/02-role.yaml
  manifests/05-deployment.yaml
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/services.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/stub/handler.go
  pkg/utils/utils.go
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#85 use DeepCopy() instead of creating new struct
  pkg/k8shandler/rbac.go
Labels: approved, lgtm, size/S

#87 Use ZeroRedundancy as the default in hack/cr.yaml
  hack/cr.yaml
Labels: approved, lgtm, size/XS

#90 Update Alerting rules
  files/prometheus_alerts.yml
Labels: approved, lgtm, size/S

#88 Fixup -- merge master into master-post-release
  README.md
  files/prometheus_alerts.yml
  hack/cr.yaml
  hack/deploy-setup.sh
  hack/prometheus-rules.yaml
  hack/test-e2e.sh
  manifests/02-role.yaml
  manifests/05-deployment.yaml
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/services.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/stub/handler.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/XXL

#91 Adding missing roles for eo sa fixing failing e2e tests
  hack/test-e2e.sh
  manifests/02-role.yaml
Labels: approved, lgtm, size/S

#96 Fix diagram link
  README.md
Labels: approved, lgtm, size/XS

#97 update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#98 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#94 add manifest for marketplace
  Dockerfile
  controller-manifests/elasticsearch-operator.package.yaml
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  controller-manifests/elasticsearches.crd.yaml
Labels: approved, lgtm, size/L

#99 Revert "add manifest for marketplace"
  Dockerfile
  controller-manifests/elasticsearch-operator.package.yaml
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  controller-manifests/elasticsearches.crd.yaml
Labels: approved, lgtm, size/L

#100 remove EO from CVO build pipeline
  Dockerfile
Labels: approved, lgtm, size/XS

#103 bug LOG-353 - oauth proxy doesnt start when deployed into different namespace
  pkg/k8shandler/rbac.go
Labels: approved, lgtm, size/XS

#80 Refactoring elasticsearch operator to improve code readability
  cmd/elasticsearch-operator/main.go
  hack/test-e2e.sh
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/render_config.go
  pkg/k8shandler/secret.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/serviceaccount.go
  pkg/k8shandler/services.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  pkg/stub/handler.go
  pkg/utils/exec.go
  pkg/utils/exec_util.go
  pkg/utils/utils.go
  test/e2e/elasticsearch_test.go
  test/e2e/main_test.go
  test/files/ca.crt
  test/files/elasticsearch.crt
  test/files/elasticsearch.key
  test/files/logging-es.crt
  test/files/logging-es.key
  test/files/system.admin.crt
  test/files/system.admin.key
  test/utils/utils.go
Labels: approved, do-not-merge/hold, lgtm, size/XXL

#104 Use test namespace for e2e tests
  hack/test-e2e.sh
Labels: approved, lgtm, ok-to-test, size/S

#92 Improved status conditions
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  test/e2e/elasticsearch_test.go
  test/e2e/main_test.go
  test/utils/utils.go
Labels: approved, lgtm, size/XL

#101 Add Marketplace manifest
  Dockerfile
  Dockerfile.rhel7
  controller-manifests/elasticsearch-operator.package.yaml
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  controller-manifests/elasticsearches.crd.yaml
Labels: approved, lgtm, size/L

#105 Bug 1691230 - Removing unnecessary output regarding pvc
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/statefulset.go
Labels: approved, lgtm, size/S

#108 fix referencing the wrong spec for status
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/XS

#106 LOG-371. Bump Elasticsearch CRD to v1
  Makefile
  cmd/elasticsearch-operator/main.go
  config/config.yaml
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  controller-manifests/elasticsearches.crd.yaml
  deploy/crds/crd.yaml
  deploy/examples/onenode-emptydir-es.yaml
  deploy/examples/onenode-hostmounted-es.yaml
  deploy/examples/onenode-pvc-es.yaml
  deploy/openshift/admin-elasticsearch-template.yaml
  deploy/openshift/elasticsearch-template.yaml
  manifests/04-crd.yaml
  pkg/apis/elasticsearch/v1/doc.go
  pkg/apis/elasticsearch/v1/register.go
  pkg/apis/elasticsearch/v1/types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/serviceaccount.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/stub/handler.go
  test/e2e/elasticsearch_test.go
  tmp/codegen/update-generated.sh
Labels: approved, lgtm, size/L

#110 Bug 1692796 - fixing refreshing node before state determines upgrade is needed
  pkg/k8shandler/deployment.go
Labels: approved, lgtm, size/S

#109 updating component to be elasticsearch instead of cr name
  pkg/k8shandler/common.go
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/XS

#111 Bug 1686173 - Use request or limit if other is not provided for resource requirements
  Makefile
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, lgtm, size/XL

#107 Bug 1691148 - assign uuid for ES nodes
  pkg/apis/elasticsearch/v1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/utils/utils.go
  test/e2e/elasticsearch_test.go
  test/utils/utils.go
Labels: approved, lgtm, size/L

#112 Bug 1691256 - updating to check proxy changes
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, lgtm, size/L

#113 Update to master 329
  Dockerfile
  Dockerfile.rhel7
  Makefile
  OWNERS
  README.md
  cmd/elasticsearch-operator/main.go
  config/config.yaml
  controller-manifests/elasticsearch-operator.package.yaml
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  controller-manifests/elasticsearches.crd.yaml
  deploy/crds/crd.yaml
  deploy/examples/onenode-emptydir-es.yaml
  deploy/examples/onenode-hostmounted-es.yaml
  deploy/examples/onenode-pvc-es.yaml
  deploy/openshift/admin-elasticsearch-template.yaml
  deploy/openshift/elasticsearch-template.yaml
  hack/test-e2e.sh
  manifests/02-role.yaml
  manifests/04-crd.yaml
  pkg/apis/elasticsearch/v1/doc.go
  pkg/apis/elasticsearch/v1/register.go
  pkg/apis/elasticsearch/v1/types.go
  pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/render_config.go
  pkg/k8shandler/secret.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/serviceaccount.go
  pkg/k8shandler/services.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  pkg/stub/handler.go
  pkg/utils/exec.go
  pkg/utils/exec_util.go
  pkg/utils/utils.go
  test/e2e/elasticsearch_test.go
  test/e2e/main_test.go
  test/files/ca.crt
  test/files/elasticsearch.crt
  test/files/elasticsearch.key
  test/files/logging-es.crt
  test/files/logging-es.key
  test/files/system.admin.crt
  test/files/system.admin.key
  test/utils/utils.go
  tmp/codegen/update-generated.sh
Labels: approved, lgtm, size/XXL
