Repository openshift/elasticsearch-operator, pull requests merged in 2019-01, with the labels that each got.

#56 fix LOG-312. Default kibana.index_mode to shared_ops
  pkg/k8shandler/defaults.go
Labels: approved, lgtm, size/XS

#58 Updating storageclass to be inline for json formatting
  pkg/apis/elasticsearch/v1alpha1/types.go
Labels: approved, lgtm, size/XS

#54 renamed parts of the CRD
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/M

#60 fix 166078. Correct the CACert file for servicemonitor
  pkg/k8shandler/service_monitor.go
Labels: approved, lgtm, size/XS

#61 update OWNERS and always format on build
  Makefile
  OWNERS
Labels: approved, lgtm, size/S

#63 fix the default image available in quay
  Makefile
  deploy/openshift/elasticsearch-template.yaml
  deploy/operator.yaml
  hack/common
  manifests/05-deployment.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#64 Guard against array index ouf of bound error
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
Labels: approved, lgtm, size/M

#66 Updating storage spec
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/service_monitor.go
Labels: approved, lgtm, size/M

#65 support buildconfigs and no image build deployments
  Makefile
  hack/common
  hack/deploy-image.sh
  hack/deploy-setup.sh
  hack/image-stream-build-config-template.yaml
  hack/undeploy.sh
Labels: approved, lgtm, size/M

#72 Removing need to use the SDK to do e2e tests, fixing broken tests
  Makefile
  hack/test-e2e.sh
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/S

#69 added a few comments and small fixes
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/M

#73 All nodes have to be created from the same Image
  pkg/apis/elasticsearch/v1alpha1/types.go
  pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/desirednodestate.go
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/M

#75 Bugfix: added name to es svc port and configured that name for service monitor
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/services.go
Labels: approved, lgtm, size/XS

#74 Updating es manifest to allow it to watch all namespaces
  hack/undeploy.sh
  manifests/02-role.yaml
  manifests/03-role-bindings.yaml
  manifests/05-deployment.yaml
Labels: approved, lgtm, size/S

#77 Don't use the sdk for exposing operator's metrics
  cmd/elasticsearch-operator/main.go
Labels: approved, lgtm, size/XS
