Repository openshift/elasticsearch-operator, pull requests merged in 2019-07, with the labels that each got.

#171 Bug 1697728 - updating the index template and existing indices replica count
  pkg/k8shandler/cluster.go
  pkg/k8shandler/elasticsearch.go
Labels: approved, lgtm, size/L

#168 bug 1724833: clean up 4.1 channel manifests
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/art.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#174 Adding support to set tolerations for es nodes and common
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, lgtm, size/L

#176 Bug 1725249: Updating to not set CPU limit unless it is explicitly set
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#162 [release-4.1] Bug 1711044: Remove nodes that arent in CR
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#179 Introduce gosec for security checks
  Makefile
  pkg/k8shandler/elasticsearch.go
Labels: approved, lgtm, size/XS
