Repository openshift/elasticsearch-operator, pull requests merged in 2019-12, with the labels that each got.

#193 Bug 1765807: Add subject per ES instance to es-proxy cluster role binding
  pkg/k8shandler/rbac.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/M

#207 bump csv to 4.4
  Dockerfile
  hack/common
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.4/elasticsearches.crd.yaml
  manifests/4.4/image-references
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/S

#210 LOG-597. Impl IndexManagement Spec
  manifests/4.4/elasticsearches.crd.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/index_management_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
Labels: approved, feature/es6x, lgtm, size/XL
