Repository openshift/elasticsearch-operator, pull requests merged in 2019-08, with the labels that each got.

#181 Bug 1740447: Only set resource limits when value is greater then zero
  Makefile
  pkg/k8shandler/common_test.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
  pkg/k8shandler/elasticsearch.go
  pkg/logger/logger.go
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm, release/4.2, size/L

#184 Update to master
  Dockerfile
  Dockerfile.rhel7
  Gopkg.lock
  Makefile
  OWNERS
  README.md
  cmd/manager/main.go
  controller-manifests/elasticsearch-operator.package.yaml
  hack/deploy-setup.sh
  hack/deploy.sh
  manifests/4.2/elasticsearch-operator.v4.2.0.clusterserviceversion.yaml
  manifests/4.2/elasticsearches.crd.yaml
  manifests/4.2/image-references
  manifests/art.yaml
  manifests/elasticsearch-operator.package.yaml
  manifests/latest
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/elasticsearch_test.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  pkg/logger/logger.go
  test/files/emptyToken
  test/files/testToken
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/swagger.go
Labels: approved, lgtm, size/XXL

#183 Ignore .idea folder
  .gitignore
Labels: approved, lgtm, size/XS

#182 Bug 1741350: Set resource limits if they are greater then 0
  Makefile
  pkg/k8shandler/common_test.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm, release/4.1, size/L

#185 channel name must be a string
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/XS

#173 Bug 1697728 - Fix template replica update
  Gopkg.lock
  hack/test-e2e-image.yaml
  hack/test-e2e-wip.sh
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/elasticsearch_helper.go
  test/e2e/elasticsearch_test.go
  test/files/Dockerfile.centos7
  test/files/e2e-test-pod.yaml
  test/files/test-e2e.sh
  test/utils/utils.go
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/cmd/json-patch/file_flag.go
  vendor/github.com/evanphx/json-patch/cmd/json-patch/main.go
  vendor/github.com/evanphx/json-patch/errors.go
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/inhies/go-bytesize/LICENSE
  vendor/github.com/inhies/go-bytesize/bytesize.go
Labels: approved, lgtm, size/XXL
