Repository openshift/elasticsearch-operator, pull requests merged in 2019-11, with the labels that each got.

#195 Bug 1765803: Add subject per ES instance to es-proxy cluster role binding
  pkg/k8shandler/elasticsearch_helper.go
  pkg/k8shandler/rbac.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#196 Bug 1768936: set minikube version
  manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, kind/bug, lgtm, release/4.3, size/XS

#197 fix image building for devs
  hack/common
Labels: approved, lgtm, size/S

#200 Bump golang base and remove unused Dockerfile.rhel7
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, release/4.3, size/S

#199 fix up make deploy to be OLM style
  Makefile
  hack/common
  hack/deploy-image.sh
  hack/deploy.sh
  hack/lib/build/archive.sh
  hack/lib/build/binaries.sh
  hack/lib/build/constants.sh
  hack/lib/build/environment.sh
  hack/lib/build/images.sh
  hack/lib/build/release.sh
  hack/lib/build/rpm.sh
  hack/lib/build/version.sh
  hack/lib/cleanup.sh
  hack/lib/cmd.sh
  hack/lib/compress.awk
  hack/lib/init.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/log/system.sh
  hack/lib/start.sh
  hack/lib/test/junit.sh
  hack/lib/util/docs.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/golang.sh
  hack/lib/util/logs.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  hack/testing/utils
  hack/undeploy.sh
  hack/vendor/.gitignore
  hack/vendor/olm-test-script/README.md
  hack/vendor/olm-test-script/e2e-olm.sh
  hack/vendor/olm-test-script/operatorgroup-template-global.yaml
  hack/vendor/olm-test-script/operatorgroup-template.yaml
  hack/vendor/olm-test-script/subscription.yaml
  hack/vendor/sources.txt
Labels: approved, lgtm, release/4.3, size/XXL

#201 update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#202 Bug 1753568: Dont restart cluster just because EO restarted
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#194 Bug 1765808: Add subject per ES instance to es-proxy cluster role binding
  pkg/k8shandler/elasticsearch_helper.go
  pkg/k8shandler/rbac.go
  test/e2e/elasticsearch_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/M
