Repository openshift/elasticsearch-operator, pull requests merged in 2019-02, with the labels that each got.

#78 dummy commit to force rebuild upon merge
  README.md
Labels: approved, lgtm, size/XS

#79 use quay.io for default image registry - use origin- for image prefix
  Makefile
  README.md
  deploy/openshift/elasticsearch-template.yaml
  deploy/operator.yaml
  hack/common
  hack/cr.yaml
  hack/deploy-image.sh
  hack/deploy.sh
  hack/image-stream-build-config-template.yaml
  hack/undeploy.sh
  manifests/05-deployment.yaml
  manifests/image-references
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/M

#71 fix e2e test and prepare for execution by CI
  Makefile
  README.md
  hack/test-e2e.sh
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/M

#81 Merge current master into master-post-release
  Makefile
  README.md
  cmd/elasticsearch-operator/main.go
  deploy/openshift/elasticsearch-template.yaml
  deploy/operator.yaml
  hack/common
  hack/cr.yaml
  hack/deploy-image.sh
  hack/deploy.sh
  hack/image-stream-build-config-template.yaml
  hack/test-e2e.sh
  hack/undeploy.sh
  manifests/05-deployment.yaml
  manifests/image-references
  pkg/k8shandler/desirednodestate.go
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/M

#82 fix wrong envar on elasticsearch deployment
  pkg/k8shandler/desirednodestate.go
Labels: approved, lgtm, size/XS

#83 Adding how to expose elasticsearch service with a route to README.md.
  README.md
Labels: approved, lgtm, size/S

#84 Bug 1665700: REPLICA_SHARDS should be 0 when es-node-data=1
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/XS
