Repository openshift/elasticsearch-operator, pull requests merged in 2019-05, with the labels that each got.

#129 Bug 1703546: Waiting for synced flush
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
Labels: approved, lgtm, size/S

#128 LOG-412. Update manifest for rh-certified operator pipeline
  Dockerfile
  Dockerfile.rhel7
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/4.1/elasticsearches.crd.yaml
  manifests/4.1/image-references
  manifests/elasticsearch-operator.package.yaml
  manifests/latest
Labels: approved, lgtm, size/S

#132 add elasticsearch image to manifest and operator env vars
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  pkg/k8shandler/common.go
Labels: approved, lgtm, size/XS

#133 Bug 1707323: Operator may attempt to write into nil map
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, lgtm, size/L

#136 Ff 41 to master
  Dockerfile
  Dockerfile.rhel7
  README.md
  hack/common
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/4.1/elasticsearches.crd.yaml
  manifests/4.1/image-references
  manifests/elasticsearch-operator.package.yaml
  manifests/latest
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
Labels: approved, lgtm, size/L

#138 fix manifest yaml
  manifests/4.1/image-references
Labels: approved, lgtm, size/XS

#135 fixing required deployment env var in manifest
  controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#139 Bug 1707465: Adding disk-pressure toleration for elasticsearch
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, lgtm, size/S

#140 use absolute paths for COPY commands
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/S

#141 Set Resources on the proxy container
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, lgtm, size/M

#146 allow logging CI to use make deploy
  Makefile
  hack/deploy-setup.sh
  hack/deploy.sh
Labels: approved, lgtm, size/S

#147 Rename go-run target to run
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#144 Bug 1707875 - Remove nodes that arent in CR
  Gopkg.lock
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  vendor/github.com/go-openapi/spec/items.go
  vendor/github.com/go-openapi/spec/schema.go
  vendor/github.com/go-openapi/spec/swagger.go
Labels: approved, lgtm, size/L

#142 Creating 4.1.1 csv
  manifests/4.1/elasticsearch-operator.v4.1.1.clusterserviceversion.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/L
