Repository openshift/elasticsearch-operator, pull requests merged in 2019-06, with the labels that each got.

#151 Bug 1717623 - fix CSV for OLM and ART
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/M

#154 Bug 1718731: elasticsearch operator fails to install due to missing specDescriptor
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#155 delete unnecessary 4.1.1 csv file
  manifests/4.1/elasticsearch-operator.v4.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#158 bug 1717627. bump crv to 4.1.2
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/art.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.1, size/S

#161 updating owners file
  OWNERS
Labels: approved, lgtm, size/XS

#159 Bug 1717627: fix art.yml ref to package.yaml
  manifests/art.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#160 Bug 1710404 - Removing setting a default cpu limit
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
Labels: approved, lgtm, size/M

#164 LOG-411 All pods are allocated to linux nodes
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/util.go
Labels: approved, lgtm, size/M

#165 Fixing redundancyPolicy field level in alm-examples
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/4.2/elasticsearch-operator.v4.2.0.clusterserviceversion.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/S

#167 clean up 4.2 channel
  Dockerfile
  Dockerfile.rhel7
  manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
  manifests/4.1/elasticsearches.crd.yaml
  manifests/4.1/image-references
  manifests/4.2/elasticsearch-operator.v4.2.0.clusterserviceversion.yaml
  manifests/art.yaml
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/L

#170 Bug 1725148: Updating to not set CPU limit unless it is explicitly set
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
