Repository openshift/elasticsearch-operator, pull requests merged in 2019-10, with the labels that each got.

#189 bump manifest for 4.3.0. fixes #188
  Dockerfile
  Dockerfile.rhel7
  manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
  manifests/4.3/elasticsearches.crd.yaml
  manifests/4.3/image-references
  manifests/latest
Labels: approved, lgtm, size/S

#187 Bug 1751320: Recreate nodes that have been deleted during upgrade
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#190 bump e2e test timeout to 20mins
  hack/test-e2e.sh
Labels: approved, lgtm, size/XS

#191 update package for 4.3
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, size/XS
