Repository openshift/elasticsearch-operator, pull requests merged in 2020-09, with the labels that each got.

#475 Bug 1867461: Remove cookie-refresh flag for kibana-proxy
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#476 updating bundle labels to be used for nightly
  bundle.Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#478 Bug 1875478: Rename console link section Monitoring to Observability
  pkg/k8shandler/kibana/consolelink.go
  pkg/k8shandler/kibana/kibana_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#480 Bug 1876236: Drop unused tuned.openshift.io/elasticsearch annotation
  pkg/k8shandler/common.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#481 Bug 1873652: Update cluster status after populating nodes
  pkg/k8shandler/cluster.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#482 Bug 1849564: Update kibana status for ready pods
  manifests/4.6/logging.openshift.io_kibanas_crd.yaml
  pkg/apis/logging/v1/kibana_types.go
  pkg/controller/kibana/controller.go
  pkg/k8shandler/kibana/kibanarequest.go
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#486 Bug 1878123: Bump client-go v1.18.3 to v1.18.8
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/clientcmd/client_config.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#477 Bug 1866019: Add more error checking to delete script
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#471 Bug 1868300: Updating EO to adopt existing uuids from pvcs or deployment objects if nil in CR
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/index_management.go
  pkg/k8shandler/migrations/kibana5to6.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/recovery.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#487 [release-4.5] Bug 1873158: Set kibana proxy session timeout to 24h
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#489 Documenting how to reindex from remote to recover old PVC data
  docs/pvc-recovery.md
Labels: approved, bugzilla/valid-bug, lgtm

#492 Bug 1880845: Fixed panic when dereferencing nil pointer for annotations
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#491 Add review guidelines from source google doc
  README.md
  docs/HACKING.md
  docs/REVIEW.md
Labels: approved, bugzilla/valid-bug, lgtm

#497 Bug 1882525: Resolve KeyError when determining indices to delete
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#495 [release-4.5] Bug 1881957: updating EO to adopt an existing cluster if cr nodes uuid is nil
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/migrations/kibana5to6.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/recovery.go
  pkg/k8shandler/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#484 Bug 1878032: Update cluster status after populating nodes
  pkg/k8shandler/cluster.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#502 Bug 1878305: Bump es max_header_size to address errors seen in Kibana
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#498 Bug 1880926: Fix owner references for elasticsearch CR
  pkg/indexmanagement/reconcile.go
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/dashboards.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/serviceaccount.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
