Repository openshift/elasticsearch-operator, pull requests merged in 2020-12, with the labels that each got.

#592 Added debug output for old and new indices for ES upgrade test
  hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
  hack/testing-olm/utils
Labels: bugzilla/valid-bug, lgtm

#596 [release-4.4] Bug 1906584: Removing ownerrefs from cluster scoped objects to address GC issue
  pkg/k8shandler/rbac.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#594 LOG-970: use centos as base image for docker
  Dockerfile.centos.patch
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm

#601 Bug 1906895: Remove replace directive in 5.0 CSV manifest
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#603 Bug 1885723: Allow kibana server to access OD tenantinfo
  internal/k8shandler/configmaps_test.go
  internal/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#602 Bug 1907758: Fix update replica count for logging indices only
  internal/elasticsearch/client.go
  internal/elasticsearch/replicas.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#607 [release-4.6] Bug 1909614: Allow kibana server to access OD tenantinfo
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#584 [release-4.6] Bug 1901299: Change ES Operator CSV to clarify the scope for this Operator
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, tide/merge-method-squash
