Repository openshift/elasticsearch-operator, pull requests merged in 2020-02, with the labels that each got.

#220 Master into es6
  Makefile
  OWNERS
  hack/cert_generation.sh
  hack/test-e2e-wip.sh
  hack/test-e2e.sh
  hack/testing/test-001-operator-sdk-e2e.sh
  hack/testing/utils
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  test/e2e/elasticsearch_test.go
  test/files/ca.crt
  test/files/elasticsearch.crt
  test/files/elasticsearch.key
  test/files/logging-es.crt
  test/files/logging-es.key
  test/files/system.admin.crt
  test/files/system.admin.key
Labels: approved, feature/es6x, lgtm, size/XL

#233 Bug 1799051: Add OLM annotations for ui hints
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, release/4.4, size/XS

#215 LOG-571: Add Indexmanagement cronjobs
  Makefile
  hack/cr.yaml
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/indexmanagement/converters.go
  pkg/indexmanagement/converters_test.go
  pkg/indexmanagement/indexmanagement_suite_test.go
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/reconcile_test.go
  pkg/indexmanagement/scripts.go
  pkg/indexmanagement/validations.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/index_management.go
  pkg/k8shandler/index_management_test.go
  pkg/k8shandler/util.go
  pkg/logger/logger.go
  pkg/types/elasticsearch/types.go
  pkg/types/k8s/configmap.go
  pkg/utils/comparators/envvars.go
  pkg/utils/comparators/envvars_test.go
  pkg/utils/comparators/maps.go
  pkg/utils/comparators/resources.go
  pkg/utils/comparators/tolerations.go
  pkg/utils/utils.go
  test/helpers/runtime/client.go
Labels: approved, feature/es6x, lgtm, release/4.5, size/XXL

#236 Bug 1799051: Add OLM annotations for ui hints
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, release/4.4

#238 Bug 1803147: fix skip range for ART
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, release/4.4

#229 Adding logic to add alias for old indices to match new data structure
  pkg/k8shandler/cluster.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/elasticsearch_test.go
Labels: approved, lgtm, size/L

#240 Bug 1804166: Update minKubeVersion for 4.4
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, release/4.4, size/XS

#239 Reduce deploy-example verbosity
  Makefile
  hack/build-image.sh
  hack/cert_generation.sh
  hack/deploy-image.sh
  hack/deploy-setup.sh
  hack/deploy.sh
  hack/test-e2e.sh
  hack/undeploy.sh
Labels: approved, lgtm, size/M

#227 Bug 1794801: [IPv6] Application should service on Address [::]:port
  pkg/k8shandler/common.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#237 Bug 1803145: Fix incorrect olm.skipRange in 4.3 CSV
  manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.3, size/XS

#241 Bug 1804169: set minKube version for 4.3
  manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.3, size/XS

#247 bump manifest to 4.5
  Dockerfile
  hack/common
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/elasticsearches.crd.yaml
  manifests/4.5/image-references
  manifests/elasticsearch-operator.package.yaml
Labels: approved, lgtm, release/4.5, size/S

#248 Updated `logs.infra` to `logs-infra`
  hack/cr.yaml
Labels: approved, lgtm, size/XS

#246 revert ES logs to console
  pkg/k8shandler/defaults.go
Labels: approved, lgtm, size/XS

#249 Bug 1808053: Define default master url for fabric8io k8s client
  pkg/k8shandler/common.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
