Repository openshift/elasticsearch-operator, pull requests merged in 2020-08, with the labels that each got.

#435 Updating EO to use operator bundle
  Makefile
  bundle/bundle.Dockerfile
  bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
  bundle/manifests/elasticsearches.crd.yaml
  bundle/manifests/image-references
  bundle/manifests/kibanas.crd.yaml
  bundle/metadata/annotations.yaml
Labels: approved, lgtm, release/4.6

#444 Bug 1865364: alert for out of file descriptors
  files/prometheus_alerts.yml
  pkg/k8shandler/prometheus_rule.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#436 [release-4.5] Bug 1861529: fixing rollout detection for deployments
  pkg/k8shandler/deployment.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/util.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#440 LOG-800 - Consolidating Kibana controllers into single file
  pkg/constants/constants.go
  pkg/controller/add_controllers.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibanasecret/controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/trustedcabundle/controller.go
  pkg/k8shandler/dashboards.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, lgtm

#445 Fix go version declaration in go.mod
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#433 [release-4.3] Bug 1860164: Disable indices level metrics in Prometheu…
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#442 Add elasticsearch and kibana CRD generation for via operator-sdk
  .bingo/Variables.mk
  .bingo/opm.mod
  .bingo/variables.env
  Makefile
  bundle/manifests/crd-drop-status-validation-patch.yaml
  bundle/manifests/elasticsearches.crd.yaml
  bundle/manifests/kibanas.crd.yaml
  bundle/manifests/kustomization.yaml
  bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml
  bundle/manifests/logging.openshift.io_kibanas_crd.yaml
  hack/generate-crd.sh
  manifests/4.6/crd-drop-status-validation-patch.yaml
  manifests/4.6/elasticsearches.crd.yaml
  manifests/4.6/kibanas.crd.yaml
  manifests/4.6/kustomization.yaml
  manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.6/logging.openshift.io_kibanas_crd.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/index_management_types.go
  pkg/apis/logging/v1/kibana_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#446 Fixing up bundle and make target
  Makefile
  bundle.Dockerfile
  bundle/manifests/image-references
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#448 Bug 1856502: Fixing rollout of nodes when proxy resources are updated
  pkg/k8shandler/deployment.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/utils/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#453 Bug 1868282: adding redundancy validation based on number of data nodes
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#454 Bug 1866019: Delete indices in batches
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#449 Add Flood Stage Watermark alert
  files/prometheus_alerts.yml
Labels: approved, lgtm

#458 Bug 1869117: fixing alerts formatting, add unit test to validate
  files/prometheus_alerts.yml
  pkg/k8shandler/prometheus_rule_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#455 Bug 1868280: fixing csv permissions to allow creation of servicemonitor object
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#459 require less resources for e2e testing
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/utils.go
Labels: approved, bugzilla/valid-bug, lgtm

#460 adding bundle validation and fixing validation
  Makefile
  bundle/manifests/crd-drop-status-validation-patch.yaml
  bundle/manifests/kustomization.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#465 Cleanup vendor directory
  go.mod
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/flags.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/kube_helpers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/zap/zap.go
Labels: approved, bugzilla/valid-bug, lgtm

#464 make tests less verbose
  Makefile
  hack/testing-olm/test-001-operator-sdk-e2e.sh
Labels: approved, bugzilla/valid-bug, lgtm

#467 Bug 1867461: Adding in cookie refresh and removing prompt for provider button
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#470 Bug 1866019: Remove space from joining deleting indices call
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#466 Add access control docs for ES6
  docs/access-control.md
  docs/images/access-control.svg
  docs/troubleshooting.md
Labels: approved, lgtm

#468 Bug 1871737: Update status using subresource /status
  bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
  bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml
  bundle/manifests/logging.openshift.io_kibanas_crd.yaml
  hack/generate-crd.sh
  manifests/4.6/crd-drop-status-validation-patch.yaml
  manifests/4.6/kustomization.yaml
  manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.6/logging.openshift.io_kibanas_crd.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/kibana_types.go
  pkg/controller/elasticsearch/controller.go
  pkg/k8shandler/status.go
  test/utils/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#447 Bug 1871737: Upgrade CRD apiVersion apiextensions.k8s.io from v1beta1 to v1
  bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml
  bundle/manifests/logging.openshift.io_kibanas_crd.yaml
  hack/generate-crd.sh
  manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.6/logging.openshift.io_kibanas_crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#472 Bug 1874081: Fixed 4.4->4.5 upgrade test
  hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#473 Bug 1873013: fix disk watermark alerts
  files/prometheus_alerts.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
