Repository openshift/elasticsearch-operator, pull requests merged in 2020-04, with the labels that each got.

#292 Updating label selector building to not accidentally grab curatorcronjob
  pkg/indexmanagement/reconcile.go
Labels: approved, lgtm, release/4.5

#293 Fixing kibana owner refs
  pkg/k8shandler/kibana/rbac.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
  pkg/k8shandler/kibana/serviceaccount.go
  pkg/k8shandler/kibana/trustedcabundle.go
Labels: approved, lgtm, release/4.5

#294 Code cleanup. Make linter a mandatory target to run
  Makefile
  pkg/controller/elasticsearch/controller.go
  pkg/controller/kibana/controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/indexmanagement/expectations_test.go
  pkg/indexmanagement/reconcile_test.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/elasticsearch_helper.go
  pkg/k8shandler/elasticsearch_test.go
  pkg/k8shandler/index_management_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/logger/logger.go
Labels: approved, lgtm

#288 Add virtual role for indexmanagement cronjobs
  pkg/indexmanagement/scripts.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/rbac.go
  pkg/types/k8s/configmap.go
  pkg/types/k8s/rbac.go
Labels: approved, lgtm, release/4.5

#296 Omit helper tool downloads for ART build process
  Makefile
Labels: approved, lgtm

#257 Bug 1803196: Replace shared config map with console link CRs
  pkg/k8shandler/kibana/consolelink.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
Labels: approved, bugzilla/valid-bug, lgtm, release/4.5, size/L

#298 Revert "257 - Replace shared config map with console link CRs"
  pkg/k8shandler/kibana/consolelink.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
Labels: approved, lgtm

#299 Fix e2e olm registry env vars for kibana and oauth-proxy
  Makefile
  olm_deploy/operatorregistry/registry-deployment.yaml
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm

#301 update owner file to include component
  OWNERS
Labels: approved, lgtm, release/4.5

#302 fixing auth sar for sg_role_admin
  pkg/k8shandler/common.go
Labels: approved, lgtm

#263 Bug 1812920: Adding nodeSelector to operator deployment
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.4, size/XS

#303 Adjusting IM cj specs for namespace noise
  pkg/indexmanagement/reconcile.go
Labels: approved, lgtm

#304 Overwrite pull policy for local olm based E2E tests
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm

#306 unifying tests to use the same TEST_NAMESPACE var
  Makefile
  hack/testing-olm/test-200-verify-es-metrics-access.sh
Labels: approved, lgtm

#305 Kibana isn't tied to openshift-logging namespace anymore
  pkg/constants/constants.go
  pkg/controller/kibanasecret/controller.go
  pkg/controller/trustedcabundle/controller.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/reconciler_test.go
Labels: approved, lgtm

#308 rename crons for index managment
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/reconcile_test.go
Labels: approved, lgtm, release/4.5

#307 cleaning up and optimizing delete cronjob
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/scripts.go
Labels: approved, lgtm

#310 Enhance debug experience for E2E operator registry
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  hack/testing-olm/utils
Labels: approved, lgtm

#317 make crd have a valid schema
  manifests/4.5/elasticsearches.crd.yaml
  manifests/4.5/kibanas.crd.yaml
  test/e2e-olm/elasticsearch_test.go
Labels: approved, release/4.5

#309 Bug 1825955: Fixing proxy SAR to match for admin_reader
  pkg/k8shandler/common.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#316 Bug 1826781: Added ENV comparison for ES deployment and stateful set
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#315 Bug 1823606: Updating kibana update to also check proxy container env
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/reconciler_test.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#320 Bug 1826451: Make indexmanagment rely on packaged es image
  manifests/4.5/elasticsearches.crd.yaml
  pkg/constants/constants.go
  pkg/indexmanagement/reconcile.go
  pkg/k8shandler/common.go
  pkg/k8shandler/defaults.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm, release/4.5

#322 Bug 1827063: Grant perm to set owner ref to metrics Service resource
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#328 Update dockerfile to get registry Binary from bin
  olm_deploy/operatorregistry/Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#300 Bug 1803196: Replace shared config map with console link CRs
  go.mod
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  pkg/k8shandler/kibana/consolelink.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/kibana_test.go
  test/e2e-olm/utils.go
  test/utils/utils.go
Labels: approved, bugzilla/valid-bug, lgtm

#327 Bug 1827690: Adding ImagePullBackOff condition to unschedulableNodes
  pkg/k8shandler/cluster.go
  pkg/k8shandler/status.go
Labels: approved, backport/4.3, backport/4.4, bugzilla/high, bugzilla/valid-bug, lgtm

#321 remove at least one level of dead code
  Makefile
  hack/lib/cleanup.sh
  hack/test-e2e.sh
  hack/testing/test-001-operator-sdk-e2e.sh
  hack/testing/test-200-verify-es-metrics-access.sh
  hack/testing/utils
Labels: approved, bugzilla/valid-bug, lgtm

#331 Fix leftover reference to hack/testing/utils
  hack/common
Labels: approved, bugzilla/valid-bug, lgtm

#326 simplify deploy using registry
  Makefile
  hack/deploy-image.sh
  hack/deploy.sh
  hack/undeploy.sh
  olm_deploy/scripts/catalog-build.sh
Labels: approved, bugzilla/valid-bug, lgtm
