Repository openshift/elasticsearch-operator, pull requests merged in 2020-05, with the labels that each got.

#334 fix make deploy on 4.4
  hack/build-image.sh
  hack/common
  hack/deploy-image.sh
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#341 Bug 1809498: Compare container args to determine update of node
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch/elasticsearch_suite_test.go
  pkg/k8shandler/elasticsearch/resources_test.go
  pkg/k8shandler/elasticsearch/update.go
  pkg/k8shandler/elasticsearch/update_test.go
  pkg/k8shandler/statefulset.go
  test/utils/utils.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#336 Bug 1824006: Backported fix for ES ENV
  hack/test-e2e.sh
  hack/testing/test-001-operator-sdk-e2e.sh
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/utils/comparators/envvars.go
  pkg/utils/comparators/envvars_test.go
  test/e2e/elasticsearch_test.go
  test/utils/utils.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#345 Bug 1809498: Fixes to support upgrade from 4.4 to 4.5
  cmd/manager/main.go
  manifests/4.5/kibanas.crd.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/kibana_types.go
  pkg/controller/elasticsearch/controller.go
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
  pkg/k8shandler/elasticsearch/elasticsearch_suite_test.go
  pkg/k8shandler/elasticsearch/update.go
  pkg/k8shandler/elasticsearch/update_test.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/statefulset.go
  test/utils/utils.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#346 Bug 1809498: Adding logic to add alias for old indices to match new data structure
  pkg/k8shandler/cluster.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#348 Bug 1833142: Renamed kibana CR instance
  pkg/constants/constants.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#352 Bug 1824006: fix update of env vars
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#351 Bug 1834311: Fix trusted ca bundle and hash reconciliation
  pkg/controller/proxyconfig/controller.go
  pkg/controller/trustedcabundle/controller.go
  pkg/k8shandler/kibana/configmap.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/trustedcabundle.go
Labels: approved, backport/4.4, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#354 Bug 1832125: Expose es-metrics svc target port in proxy container
  hack/deploy-example-secrets.sh
  hack/test-e2e-olm.sh
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/service.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#353 Bug 1826781: Add test to support container checks
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#359 bug 1817592: downstream kibana name is logging-kibana6
  manifests/4.5/image-references
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#355 Bug 1836452: Updating upgrade policy to allow yellow and set only primaries
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/utils/comparators/envvars.go
  pkg/utils/utils.go
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/utils.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#363 Fixed EO E2E test
  test/e2e-olm/elasticsearch_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#349 Added proper synchronization for oc port-forward to the remote image registry
  hack/deploy-image.sh
  olm_deploy/scripts/catalog-build.sh
Labels: approved, bugzilla/valid-bug, lgtm

#347 Bug 1833145: Set network policy when doing upgrades to prevent connections
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#360 Bug 1835083: Add missing mTLS credentials for indexmanagement jobs
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#358 Bug 1836866: Fixed deployment trigger when replicas changed
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/reconciler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#357 Bug 1835903: Reindex kibana index for kibana6
  pkg/constants/constants.go
  pkg/controller/kibana/controller.go
  pkg/controller/kibanasecret/controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/trustedcabundle/controller.go
  pkg/elasticsearch/client.go
  pkg/elasticsearch/cluster.go
  pkg/elasticsearch/cluster_test.go
  pkg/elasticsearch/indices.go
  pkg/elasticsearch/indices_test.go
  pkg/elasticsearch/templates_test.go
  pkg/k8shandler/cr.go
  pkg/k8shandler/index_management_test.go
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/kibanarequest.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/migrations/kibana5to6.go
  pkg/k8shandler/migrations/kibana5to6_test.go
  pkg/k8shandler/migrations/migrations.go
  pkg/k8shandler/migrations/migrations_suite_test.go
  pkg/k8shandler/migrations/migrations_test.go
  pkg/types/elasticsearch/types.go
  pkg/utils/utils.go
  test/e2e-olm/utils.go
  test/helpers/elasticsearch.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, feature/es6x, lgtm

#362 Bug 1837323: Fixed EO crash
  pkg/elasticsearch/indices.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#366 Bug 1833268: revert logs-* aliases to logs.*
  hack/cr.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#365 Bug 1840909: Updating cert restarts to also adhere to primaries instead of none
  pkg/k8shandler/cluster.go
  pkg/k8shandler/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#364 Bug 1837867: configure default and admin roles for proxy
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
