Repository openshift/elasticsearch-operator, pull requests merged in 2020-07, with the labels that each got.

#410 Bug 1848696: disable system_call_filter check on non-amd64 architectures
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#409 Cleanup old E2E files
  hack/test-e2e-image.yaml
  hack/vendor/.gitignore
  hack/vendor/olm-test-script/README.md
  hack/vendor/olm-test-script/e2e-olm.sh
  hack/vendor/olm-test-script/operatorgroup-template-global.yaml
  hack/vendor/olm-test-script/operatorgroup-template.yaml
  hack/vendor/olm-test-script/subscription.yaml
  hack/vendor/sources.txt
  test/e2e/elasticsearch_test.go
  test/e2e/main_test.go
  test/files/Dockerfile.centos7
  test/files/e2e-test-pod.yaml
  test/files/test-e2e.sh
Labels: approved, lgtm

#412 Refactor E2E tests to separate test cases
  Makefile
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  pkg/elasticsearch/client.go
  pkg/k8shandler/kibana/reconciler.go
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/kibana_test.go
  test/e2e-olm/main_test.go
  test/e2e-olm/utils.go
  test/utils/utils.go
Labels: approved, lgtm

#400 Refactoring EO for readability and efficiency
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/elasticsearch/client.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/clusterrestart.go
  pkg/k8shandler/clusterrestart_test.go
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/confimaps_test.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
  pkg/k8shandler/index_management.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
Labels: approved, lgtm

#406 Bug 1850546: Add support label for s390x & ppc64le
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#423 updating to label ns instead of annotate
  olm_deploy/scripts/operator-install.sh
Labels: approved, lgtm

#414 Bug 1852889: Bump minKubeVersion to 1.18.3
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#417 Check pod spec for E2E elasticsearch cluster restart test cases
  go.mod
  test/e2e-olm/elasticsearch_test.go
  test/utils/utils.go
Labels: approved, lgtm

#420 [release-4.5] Bug 1855312: Add support label for s390x & ppc64le
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#418 [release-4.4] Bug 1854472: k8shandler: disable system_call_filter check on non-amd64 architectures
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test

#415 [release-4.5] Bug 1854262: k8shandler: disable system_call_filter check on non-amd64 architectures
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test

#428 Revert "Bug 1852889: Bump minKubeVersion to 1.18.3"
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#426 Bug 1856502: Add ES-Proxy Resources to Elasticsearch CR
  manifests/4.6/elasticsearches.crd.yaml
  olm_deploy/scripts/operator-install.sh
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#427 Bug 1858249: Disable indices level metrics in Prometheus exporter output
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#425 Bug 1857826: Assume average log message is 1K
  pkg/constants/constants.go
  pkg/indexmanagement/converters.go
  pkg/indexmanagement/converters_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#419 [release-4.3] Bug 1855072: k8shandler: disable system_call_filter check on non-amd64 architectures
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#434 Bug 1852889: Revert "Merge pull request #428 from periklis/revert-minkubeversion-1-18-3"
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#429 [release-4.5] Bug 1859991: Disable indices level metrics in Prometheus exporter output
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#431 [release-4.5] Bug 1860135: Assume average log message is 1K
  pkg/constants/constants.go
  pkg/indexmanagement/converters.go
  pkg/indexmanagement/converters_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#438 LOG-700 add elasticsearch metrics dashboard
  Dockerfile
  files/dashboards/logging-dashboard-elasticsearch.json
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/dashboards.go
  pkg/k8shandler/reconciler.go
  pkg/k8shandler/status.go
Labels: approved, lgtm

#439 Pin development tools with bingo
  .bingo/.gitignore
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/go.mod
  .bingo/golangci-lint.mod
  .bingo/junitreport.mod
  .bingo/operator-sdk.mod
  .bingo/variables.env
  Dockerfile
  Makefile
  golangci.yaml
Labels: approved, lgtm

#432 [release-4.4] Bug 1860156: Disable indices level metrics in Prometheu…
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#424 Optimizing cluster.go workflow
  hack/deploy-example-secrets.sh
  hack/kibana-cr.yaml
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  pkg/k8shandler/cluster.go
  pkg/k8shandler/clusterrestart.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/k8shandler/util.go
  pkg/k8shandler/util_test.go
  test/e2e-olm/elasticsearch_test.go
  test/utils/utils.go
Labels: approved, lgtm
