Repository openshift/elasticsearch-operator, pull requests merged in 2020-03, with the labels that each got.

#253 Removed override duplicate for fsnotify package
  Gopkg.lock
  Gopkg.toml
Labels: approved, lgtm, size/XS

#255 Fixed Kibana status cluster conditions
  pkg/apis/logging/v1/kibana_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
  pkg/k8shandler/kibana/status.go
Labels: approved, lgtm, size/L

#256 fix manifest so it has proper structure
  Dockerfile
Labels: approved, lgtm, release/4.5, size/XS

#225 LOG-620 Replace proxy
  Makefile
  hack/common
  hack/cr.yaml
  hack/deploy-example-secrets.sh
  hack/testing/test-001-operator-sdk-e2e.sh
  hack/testing/test-200-verify-es-metrics-access.sh
  hack/testing/utils
  manifests/05-deployment.yaml
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/image-references
  pkg/k8shandler/common.go
  pkg/k8shandler/service.go
  test/e2e/elasticsearch_test.go
Labels: approved, feature/es6x, lgtm, release/4.5, size/L

#258 Use consistent image naming for elasticsearch-proxy
  hack/vendor/olm-test-script/operatorgroup-template-global.yaml
  hack/vendor/olm-test-script/operatorgroup-template.yaml
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/image-references
  pkg/k8shandler/common.go
Labels: approved, lgtm, size/S

#259 Use origin- prefix for quay.io image references
  hack/testing/test-001-operator-sdk-e2e.sh
  manifests/05-deployment.yaml
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/4.5/image-references
  pkg/k8shandler/common.go
Labels: approved, lgtm, size/S

#260 Add missing logging-es cert and auth whitelisted names for proxy
  pkg/k8shandler/common.go
Labels: approved, lgtm, size/S

#261 Use whitelisted subjects in RFC2253 syntax in proxy args
  hack/test-e2e.sh
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, lgtm, release/4.5, size/M

#254 Bug 1808986: Adding nodeSelector to operator deployment
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#265 Update OWNERS
  OWNERS
Labels: approved, lgtm

#264 introduce olm catalog based variant of e2e test
  Makefile
  hack/test-e2e-olm.sh
  hack/testing-olm/test-001-operator-olm-e2e.sh
  hack/testing-olm/utils
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/operatorregistry/catalog-source.yaml
  olm_deploy/operatorregistry/registry-deployment.yaml
  olm_deploy/operatorregistry/service.yaml
  olm_deploy/scripts/catalog-build.sh
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/catalog-uninstall.sh
  olm_deploy/scripts/operator-install.sh
  olm_deploy/scripts/operator-uninstall.sh
  olm_deploy/scripts/registry-init.sh
  olm_deploy/scripts/wait_for_deployment.sh
  olm_deploy/subscription/operator-group.yaml
  olm_deploy/subscription/subscription.yaml
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/main_test.go
  test/files/dummycrd.yaml
Labels: approved, lgtm

#266 fix bash syntax in olm catalog deploy script
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#252 Bug 1809511: block creation of indices with the write suffix for index management
  .gitignore
  hack/test-e2e.sh
  hack/testing/test-200-verify-es-metrics-access.sh
  hack/testing/test-657-im-block-autocreate-for-write-suffix.sh
  hack/testing/utils
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/valid-bug, lgtm, release/4.5, size/L

#269 re-enable other e2e tests
  hack/test-e2e-olm.sh
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  hack/testing-olm/utils
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#270 Bug 1811867: Fix binding to ipv6
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
  test/helpers/envvars.go
  test/helpers/yaml.go
Labels: approved, backport/4.3, backport/4.4, bugzilla/valid-bug, lgtm, release/4.5

#272 Adding in elasticsearch-operator acl to proxy
  pkg/k8shandler/common.go
Labels: approved, lgtm

#262 Provide proxy configuration for metrics TLS listener
  hack/test-e2e.sh
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/service.go
Labels: approved, lgtm, release/4.5, size/M

#274 Revert "Bug 1809511: Block creation of indices with the write suffix …
  .gitignore
  hack/testing/test-200-verify-es-metrics-access.sh
  hack/testing/test-657-im-block-autocreate-for-write-suffix.sh
  hack/testing/utils
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/valid-bug, lgtm, release/4.5

#275 default the eo operator registry image variable
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#276 remove unused variable check paths
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm

#267 Fix EO panic when response from elasticsearch is not as expected
  pkg/k8shandler/elasticsearch_helper.go
Labels: approved, lgtm, release/4.5

#273 Re-organize comments to give better CRD `description` fields.
  pkg/apis/logging/v1/elasticsearch_types.go
Labels: approved, lgtm

#278 Forward SA token to ES for auth
  pkg/k8shandler/elasticsearch_helper.go
Labels: approved, lgtm, release/4.5

#280 define a helper dockerfile for publishing the source image
  Dockerfile.src
Labels: approved, lgtm

#284 exclude im-block-test
  hack/test-e2e-olm.sh
  hack/testing-olm/utils
Labels: approved, lgtm, release/4.5

#282 remove travis related files
  .travis.yml
  .travis/prepare-environment.sh
  tests/test-insecure-cdm.sh
  tests/test-secret.yaml
  tests/test-secure-cdm.sh
  tests/utils.sh
  tests/wait-for-container.sh
  tests/wait-for-operator.sh
Labels: approved, lgtm

#286 Bug 1809511: block autocreation of indices with 'write' suffix
  hack/test-e2e-olm.sh
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, lgtm, release/4.5

#290 Fix missing GOROOT for CRD/API generation
  Makefile
Labels: approved, lgtm, release/4.5
