Repository openshift/elasticsearch-operator, pull requests merged in 2020-10, with the labels that each got.

#493 Bug 1880926: Stop rescheduling non-existing nodes
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#508 Bug 1878305: further increasing http max_header_size
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#488 Bug 1868675: Delete indices in batches
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#511 Bug 1883719: Bulk statistics are recorded under index threadpool
  files/prometheus_alerts.yml
  files/prometheus_rules.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#505 Bug 1883444: capping primary shard count at 5 for performance reasons
  pkg/elasticsearch/client.go
  pkg/elasticsearch/replicas.go
  pkg/elasticsearch/templates.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/defaults_test.go
  pkg/k8shandler/elasticsearch.go
  pkg/types/elasticsearch/types.go
  test/utils/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#513 Fixed E2E 4.4 -> 4.5 upgrade test
  hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
Labels: approved, lgtm

#509 Bug 1884477: Update bundle manifests to reflect latest CRD state
  bundle/manifests/logging.openshift.io_kibanas_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#521 Bug 1886796: Fix in-place filtering missing status nodes
  pkg/k8shandler/status.go
  pkg/k8shandler/status_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#522 LOG-910: Add unit test validation for Prometheus rules and alerts
  .bingo/Variables.mk
  .bingo/promtool.mod
  .bingo/variables.env
  Makefile
Labels: approved, lgtm

#523 Bug 1886856: Increase es proxy default memory resources to 256Mi
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#512 Bug 1881709: Add connect timeout for IM jobs
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#531 Bug 1887357: Correctly updating the elasticsearch node conditions
  pkg/k8shandler/status.go
  pkg/k8shandler/status_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#534 Bug 1880926: Correctly updating the elasticsearch node conditions
  pkg/k8shandler/status.go
  pkg/k8shandler/status_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#518 Use default storageclass for elasticsearch pvc if none defined in CR
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/utils.go
Labels: approved, lgtm

#526 Bug 1886907: Flood stage watermark alert: Remove wording that read-only index block is auto-released
  files/prometheus_alerts.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#535 Deployment script improvment
  docs/HACKING.md
  hack/common
  olm_deploy/scripts/catalog-build.sh
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/catalog-uninstall.sh
  olm_deploy/scripts/operator-install.sh
  olm_deploy/scripts/operator-uninstall.sh
  olm_deploy/scripts/wait_for_deployment.sh
Labels: approved, lgtm

#533 Bug 1883719: Bulk statistics are recorded under write threadpool
  files/prometheus_alerts.yml
  files/prometheus_rules.yml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#496 Bug 1882495: Block auto index creation for indices with "-write" suffix
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#504 [release-4.5] Bug 1883357: Bump es max_header_size to address errors seen in Kibana
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#544 Add GH pull request template
  .github/pull_request_template.md
Labels: approved, lgtm

#545 Bug 1889573: Fix nil map in updating kibana resource
  pkg/utils/resources.go
  pkg/utils/utils_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#541 Examples: Allow deployment of es example in a different namespace
  Makefile
  bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
  docs/HACKING.md
Labels: approved, lgtm

#543 GitHub bug issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, lgtm

#538 Doc: fix steps of deploying image to oc cluster
  docs/HACKING.md
Labels: approved, lgtm

#506 Bug 1883777: Fix owner references for elasticsearch CR
  pkg/k8shandler/common.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/prometheus_rule.go
  pkg/k8shandler/rbac.go
  pkg/k8shandler/service.go
  pkg/k8shandler/service_monitor.go
  pkg/k8shandler/serviceaccount.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#510 Bug 1883777: Stop rescheduling non-existing nodes
  go.mod
  go.sum
  pkg/k8shandler/cluster.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#532 Bug 1883777: Fix in-place filtering missing status nodes
  go.mod
  pkg/k8shandler/status.go
  pkg/k8shandler/status_test.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/format.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/reporter.go
  vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
  vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#503 [release-4.4] Bug 1883355: updating EO to adopt an existing cluster if cr nodes uuid is nil
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/persistentvolumeclaims.go
  pkg/k8shandler/recovery.go
  pkg/k8shandler/util.go
  pkg/utils/resources.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#546 Reduce the footprint of the elasticsearch-operator-registry image
  olm_deploy/operatorregistry/Dockerfile
Labels: approved, lgtm

#550 Bingo: fix get path for operator-sdk
  .bingo/Variables.mk
  .bingo/operator-sdk.mod
Labels: approved, lgtm

#555 Added custom index verification for ES upgrade test
  hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
Labels: approved, lgtm

#549 Bug 1890825: watch route deletion in kibana controller
  pkg/controller/kibana/controller.go
  test/e2e-olm/kibana_test.go
  test/e2e-olm/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, tide/merge-method-squash

#548 Bug 1892755: Update Elasticsearch dashboard
  files/dashboards/logging-dashboard-elasticsearch.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#529 Bump OCP version to 4.7
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  manifests/4.7/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/image-references
  manifests/4.7/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.7/logging.openshift.io_kibanas_crd.yaml
  manifests/elasticsearch-operator.package.yaml
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, do-not-merge/hold, lgtm

#542 LOG-967: Add service monitor endpoint for es-proxy prometheus metrics
  pkg/k8shandler/service_monitor.go
Labels: approved, lgtm

#552 Bug 1891666: LOG-900: Updating hacking docs and csv to be more up-to-date
  .github/pull_request_template.md
  docs/HACKING.md
  manifests/4.7/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
