Repository openshift/elasticsearch-operator, pull requests merged in 2020-01, with the labels that each got.

#213 fix prometheus crd location
  hack/test-e2e-wip.sh
  hack/test-e2e.sh
Labels: approved, lgtm, release/4.4, size/XS

#209 support for es6 configmap
  pkg/k8shandler/configuration_tmpl.go
Labels: approved, feature/es6x, lgtm, release/4.4, size/S

#217 Add make target for example secret for hacking
  Makefile
  hack/cert_generation.sh
  test/e2e/elasticsearch_test.go
  test/files/ca.crt
  test/files/elasticsearch.crt
  test/files/elasticsearch.key
  test/files/logging-es.crt
  test/files/logging-es.key
  test/files/system.admin.crt
  test/files/system.admin.key
Labels: approved, lgtm, release/4.4, size/XL

#221 move e2e test so we can write other e2e tests
  Makefile
  hack/test-e2e-wip.sh
  hack/test-e2e.sh
  hack/testing/test-001-operator-sdk-e2e.sh
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, release/4.4, size/L

#222 update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#223 add logAppender annotation for development
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  test/e2e/elasticsearch_test.go
Labels: approved, lgtm, size/S

#218 Bug 1789261: Dont restart cluster just because EO restarted
  pkg/k8shandler/deployment.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, kind/bug, lgtm, release/4.2, size/S

#224 dump pod test logs
  hack/testing/test-001-operator-sdk-e2e.sh
  hack/testing/utils
Labels: approved, lgtm, size/M

#219 Bug 1791231: Make addresses ipv6 compatible
  hack/cert_generation.sh
  pkg/k8shandler/common.go
Labels: approved, backport/4.3, bugzilla/valid-bug, lgtm, release/4.4, size/XS

#226 Update operator to expect ESv6
  README.md
  hack/cr.yaml
  hack/test-e2e.sh
  manifests/05-deployment.yaml
  manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
  manifests/4.4/image-references
  pkg/k8shandler/defaults.go
  pkg/logger/logger.go
  test/e2e/elasticsearch_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#231 update deployment to use images from defined imagestream
  Makefile
  hack/test-e2e.sh
  hack/testing/utils
  hack/vendor/olm-test-script/e2e-olm.sh
Labels: approved, bugzilla/valid-bug, feature/es6x, lgtm, size/S
