Repository openshift/elasticsearch-operator, pull requests merged in 2020-06, with the labels that each got.

#343 Removed a target namespace recommendation from the CSV
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, lgtm

#369 Bug 1842445: Drop xtrace to ensure token not visible in logs
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#372 Bug 1835083: Add mTLS credentials to rollover IM script
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#367 Bug 1841832: network policy to allow ES pod loopback and intercluster communication
  pkg/elasticsearch/client.go
  pkg/elasticsearch/cluster.go
  pkg/elasticsearch/cluster_test.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/types/elasticsearch/types.go
  pkg/utils/comparators/versions.go
  pkg/utils/comparators/versions_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#374 Revert "Bug 1835083: Add mTLS credentials to rollover IM script"
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#376 Revert "Bug 1835083: Add missing mTLS credentials for indexmanagement jobs
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#370 Bug 1842043: Stop reconciliation on ES CR not present
  pkg/controller/kibanasecret/controller.go
  pkg/controller/proxyconfig/controller.go
  pkg/controller/trustedcabundle/controller.go
  pkg/k8shandler/cr.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#379 Bug 1842865: Fix Reconcile loop return values
  pkg/controller/kibana/controller.go
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#383 Bug 1841832: Removing calls to enforce and relax networkpolicy
  pkg/controller/proxyconfig/controller.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/cr.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#384 Bug 1835083: Update ports if they differ from the desired
  pkg/k8shandler/deployment.go
  pkg/k8shandler/deployment_test.go
  pkg/k8shandler/elasticsearch_suite_test.go
  pkg/k8shandler/kibana/k8shandler_suite_test.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#386 [release-4.5] Bug 1843715: Perform a full cluster restart when upgrading ES maj versions
  pkg/controller/proxyconfig/controller.go
  pkg/elasticsearch/client.go
  pkg/elasticsearch/cluster.go
  pkg/elasticsearch/cluster_test.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/common.go
  pkg/k8shandler/cr.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/types/elasticsearch/types.go
  pkg/utils/comparators/versions.go
  pkg/utils/comparators/versions_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#385 Bug 1845539: Update skipRange constraint to 4.4.0
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#377 Bug 1842445: Drop curl verbosity in index management scripts
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#390 Bug 1834576: Fixing kibana not rolling out with secret update
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/migrations/migrations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#394 [release-4.4] Bug 1845993: Fix unnecessary restarts and harden rolling restarts
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/elasticsearch.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/utils/comparators/envvars.go
  pkg/utils/utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#395 Bug 1847413: Fix E2E olm registry migration
  olm_deploy/operatorregistry/Dockerfile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#397 Bug 1845539: Update olm.skipRange constraint to 4.4.0-0
  manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
  manifests/art.yaml
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#381 [release-4.5] Revert "Bug 1843564: Add missing mTLS credentials for indexmanagement…
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, group-lead-approved, lgtm

#398 Bug 1847450: Publish only one console link for Kibana
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
  test/e2e-olm/kibana_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#368 Bump to 4.6
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
  manifests/4.6/elasticsearches.crd.yaml
  manifests/4.6/image-references
  manifests/4.6/kibanas.crd.yaml
  manifests/elasticsearch-operator.package.yaml
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#342 Fixed log message spelling, simplified a few boolean expressions
  pkg/indexmanagement/reconcile.go
  pkg/k8shandler/index_management.go
  pkg/k8shandler/kibana/trustedcabundle.go
  pkg/utils/utils.go
Labels: approved, lgtm
