Repository openshift/elasticsearch-operator, pull requests merged in 2020-11, with the labels that each got.

#562 Remove fmt from make build because it breaks ART
  Makefile
Labels: approved, lgtm

#565 LOG-939: Add Prometheus unit testing
  Makefile
  test/files/prometheus-unit-tests/test.yml
Labels: approved, lgtm

#563 Add coverage report for test-unit target
  .gitignore
  Makefile
Labels: approved, lgtm

#568 Bug 1894632: Add ES-Proxy Resources to Elasticsearch CR
  manifests/4.5/elasticsearches.crd.yaml
  olm_deploy/scripts/operator-install.sh
  pkg/apis/logging/v1/elasticsearch_types.go
  pkg/apis/logging/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/podtemplate.go
  pkg/k8shandler/podtemplate_test.go
  pkg/k8shandler/recovery.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/util.go
  pkg/utils/resources.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#559 LOG-968: fix lint issues
  golangci.yaml
  pkg/elasticsearch/indices.go
  pkg/elasticsearch/templates.go
  pkg/indexmanagement/expectations_test.go
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/validations_test.go
  pkg/k8shandler/cluster.go
  pkg/k8shandler/clusterrestart.go
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
  pkg/k8shandler/configmaps.go
  pkg/k8shandler/defaults.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/index_management_test.go
  pkg/k8shandler/kibana/defaults.go
  pkg/k8shandler/kibana/pod_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/reconciler_test.go
  pkg/k8shandler/kibana/status.go
  pkg/k8shandler/migrations/kibana5to6.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/statefulset.go
  pkg/k8shandler/status.go
  pkg/utils/utils.go
  test/helpers/json.go
Labels: approved, lgtm

#553 Bug 1891019: Adding logic to recover from crashloopbackoff for ES pods
  pkg/k8shandler/cluster.go
  pkg/k8shandler/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#564 Add junit report for test targets
  .bingo/Variables.mk
  .bingo/go-junit-report.mod
  .bingo/junitmerge.mod
  .bingo/junitreport.mod
  .bingo/variables.env
  Makefile
  hack/lib/test/junit.sh
  hack/test-e2e-olm.sh
  hack/testing-olm/assertions
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  hack/testing-olm/utils
Labels: approved, lgtm

#570 Fixing upgrade test failures
  hack/testing-olm-upgrade/upgrade-common
  hack/testing-olm/utils
Labels: approved, lgtm

#561 LOG-951: Replace alpha svc annotation with beta
  pkg/k8shandler/service.go
  pkg/k8shandler/service_test.go
Labels: approved, lgtm

#574 Bug 1883444: Updating index template logic to cap primary shards
  pkg/k8shandler/index_management.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#573 fixing up deploying latest version available to catalog
  Makefile
  hack/testing-olm-upgrade/upgrade-common
Labels: approved, lgtm

#581 Bug 1898572: Restricting console links to clusterlogging operator use case
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
  test/e2e-olm/kibana_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#580 Bug 1899589: Updating CRD to make storage size required if storage is provided
  Makefile
  pkg/k8shandler/common.go
  pkg/k8shandler/common_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#586 Bug 1899905: Handle invalid json in delete script
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#587 Bug 1898572: Fix kibana unit tests
  Makefile
  pkg/k8shandler/kibana/kibana_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
