Repository openshift/elasticsearch-operator, pull requests merged in 2021-03, with the labels that each got.

#658 use image env vars instead of IMAGE_FORMAT
  Makefile
  hack/testing-olm-upgrade/upgrade-common
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm, release/tech-preview

#657 use image env vars instead of IMAGE_FORMAT
  Makefile
  hack/testing-olm-upgrade/upgrade-common
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm, release/5.0

#661 Remove obsolete 4.7.0 manifests
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  manifests/4.7/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/image-references
  manifests/5.0/logging.openshift.io_elasticsearches_crd.yaml
  manifests/5.0/logging.openshift.io_kibanas_crd.yaml
  manifests/5.1/elasticsearch-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/5.1/elasticsearch-operator-metrics-service_v1_service.yaml
  manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
  manifests/5.1/logging.openshift.io_elasticsearches_crd.yaml
  manifests/5.1/logging.openshift.io_kibanas_crd.yaml
  manifests/art.yaml
  manifests/elasticsearch-operator.package.yaml
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#595 Updating local cert storage path to be unique based on namespace and cluster name
  internal/elasticsearch/client.go
Labels: approved, lgtm

#644 Bug 1919075: Condense indexmanagement into single cronjob
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/reconcile_test.go
  pkg/k8shandler/index_management.go
  pkg/log/log.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.5

#656 Changing severity level of prometheus alerts
  hack/prometheus-rules.yaml
Labels: approved, lgtm

#665 Fix upgrade tests for release-5.x
  hack/testing-olm-upgrade/upgrade-common
Labels: approved, lgtm

#664 Fix upgrade tests for release-5.0
  hack/testing-olm-upgrade/upgrade-common
Labels: approved, lgtm

#663 LOG-1169: Fix no icon on EO in Operator Hub
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Labels: approved, lgtm

#666 Added icon to EO CSV
  bundle.Dockerfile
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  controllers/logging/secret_controller.go
  internal/constants/constants.go
  internal/indexmanagement/reconcile.go
  internal/indexmanagement/reconcile_test.go
  internal/k8shandler/index_management_test.go
  internal/k8shandler/secret.go
  manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
Labels: approved, lgtm

#653 Fix operator ports for metrics endpoint
  Makefile
  bundle/manifests/elasticsearch-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/elasticsearch-operator-metrics_v1_service.yaml
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
  bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/service.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/prometheus_role.yaml
  config/rbac/prometheus_role_binding.yaml
  manifests/5.1/elasticsearch-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  manifests/5.1/elasticsearch-operator-metrics_v1_service.yaml
  manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
  manifests/5.1/leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  manifests/5.1/leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/5.1/metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml
  manifests/5.1/prometheus_rbac.authorization.k8s.io_v1_role.yaml
  manifests/5.1/prometheus_rbac.authorization.k8s.io_v1_rolebinding.yaml
  manifests/5.1/proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  manifests/5.1/proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
Labels: approved, lgtm

#660 Log-316: Elasticsearch Operator Telemetry
  controllers/logging/elasticsearch_controller.go
  internal/k8shandler/cluster.go
  internal/metrics/metrics.go
  main.go
Labels: approved, lgtm

#672 Fmt Fix
  internal/metrics/metrics.go
  main.go
Labels: approved, lgtm

#676 Adding safeguards to cronjob to be more resilient to es 500 responses
  internal/indexmanagement/scripts.go
Labels: approved, lgtm

#667 BUG 1918920: requeue secret update event when the cluster is being ce…
  controllers/logging/secret_controller.go
  internal/k8shandler/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#679 Adding logic to remove any duplicate write index targets for an alias
  internal/indexmanagement/scripts.go
Labels: approved, lgtm

#662 Bug 1924657: Fix missing metrics port in manifests and bundle
  bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
  bundle/manifests/logging.openshift.io_kibanas_crd.yaml
  manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#674 Updating prometheus alert severity levels
  files/prometheus_alerts.yml
  hack/prometheus-rules.yaml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, lgtm, tide/merge-method-squash

#680 LOG-1153: Adding logic to perform rollover and delete for json write indices
  internal/indexmanagement/scripts.go
Labels: approved, lgtm

#683 Removing resource request and limits from EO deployment definition
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
Labels: approved, lgtm

#684 [release-5.0] Removing resource request and limits from EO deployment definition
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Labels: approved, lgtm
