Repository openshift/elasticsearch-operator, pull requests merged in 2021-04, with the labels that each got.

#686 Bug 1916911: make es status nullable for nodes and pods
  apis/logging/v1/elasticsearch_types.go
  bundle/manifests/logging.openshift.io_elasticsearches.yaml
  config/crd/bases/logging.openshift.io_elasticsearches.yaml
  manifests/5.1/logging.openshift.io_elasticsearches_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#687 Bug 1946776: fix es crd status incompatible when upgrading operator
  apis/logging/v1/elasticsearch_types.go
  bundle/manifests/logging.openshift.io_elasticsearches.yaml
  config/crd/bases/logging.openshift.io_elasticsearches.yaml
  manifests/5.0/logging.openshift.io_elasticsearches_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#690 Updating dockerfile to just copy necessary files for building image
  Dockerfile
  Dockerfile.centos.patch
Labels: approved, lgtm

#673 Log 1098 - Playbook for Critical Alerts
  docs/alerts.md
Labels: approved, lgtm

#669 ES configuration uses PKCS12 format instead of JKS
  docs/pvc-recovery.md
  internal/k8shandler/configmaps_test.go
  internal/k8shandler/configuration_tmpl.go
Labels: approved, lgtm

#685 Adding storage volume conditions to Elasticsearch
  apis/logging/v1/elasticsearch_types.go
  internal/k8shandler/deployment.go
  internal/k8shandler/podtemplate.go
  internal/k8shandler/statefulset.go
  internal/k8shandler/status.go
  main.go
Labels: approved, lgtm

#696 Api struct fixes and fmt fixes
  apis/logging/v1/elasticsearch_types.go
  internal/elasticsearch/client.go
  internal/elasticsearch/indices.go
  internal/k8shandler/index_management_test.go
  internal/k8shandler/migrations/kibana5to6.go
  internal/k8shandler/migrations/kibana5to6_test.go
  internal/k8shandler/status.go
  internal/types/elasticsearch/types.go
Labels: approved, lgtm

#698 LOG-1279: Add placeholder for linting tasks
  Makefile
  hack/run-linter
Labels: approved, lgtm, release/5.1

#699 LOG-981: rate limit es cluster downsizings to limit data loss
  Makefile
  internal/elasticsearch/client.go
  internal/elasticsearch/replicas.go
  internal/k8shandler/cluster.go
  internal/k8shandler/status.go
  internal/k8shandler/util.go
  internal/k8shandler/util_test.go
Labels: approved, lgtm

#700 LOG-1279: Rename linter task to lint
  Makefile
Labels: approved, lgtm

#693 Bug 1925307: Cherypicking updates to index management scripts
  Dockerfile
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/scripts/catalog-deploy.sh
  pkg/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#702 LOG-1279: Rename dup lint for dockerfile
  Makefile
  hack/lint-dockerfile
Labels: approved, lgtm

#703 Bug 1952968: Allow secret reconciler to reconcile during create
  controllers/logging/secret_controller.go
  internal/k8shandler/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#705 fixing up lint errors
  .gitignore
  Makefile
  internal/elasticsearch/client.go
  internal/elasticsearch/replicas.go
  internal/k8shandler/reconciler.go
  internal/k8shandler/statefulset.go
  internal/k8shandler/status.go
  internal/k8shandler/util.go
  internal/k8shandler/util_test.go
  main.go
  test/e2e-olm/elasticsearch_metric_test.go
  test/e2e-olm/utils.go
  test/utils/utils.go
Labels: approved, lgtm

#670 Update container registry to registry.ci.openshift.org
  hack/common
  hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm

#626 Query to pull number of logs per project
  docs/troubleshooting.md
Labels: approved, lgtm

#691 Bug 1945168: Remove hardcoded cluster local domain
  pkg/k8shandler/kibana/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#688 Bug 1946772: fix es crd status incompatible when upgrading operator
  bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml
  pkg/apis/logging/v1/elasticsearch_types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#704 Bug 1923788: Add secret reconciler to trigger restarts for secret changes
  pkg/controller/add_controllers.go
  pkg/controller/secret/controller.go
  pkg/k8shandler/deployment.go
  pkg/k8shandler/nodetypefactory.go
  pkg/k8shandler/reconciler.go
  pkg/k8shandler/statefulset.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
