Repository openshift/elasticsearch-operator, pull requests merged in 2021-06, with the labels that each got.

#722 LOG-1130: Fix duplicate container env var for policy mapping
  internal/indexmanagement/reconcile.go
Labels: approved, lgtm

#720 [release-5.1] LOG-1309: Sometimes the metric count "rolling_restart" doesn't increase after ES cluster perform rolling restart.
  internal/k8shandler/cluster.go
Labels: approved, lgtm

#726 Abort rollover when target index exists but read-only
  internal/indexmanagement/scripts.go
Labels: approved, do-not-merge/hold, lgtm

#727 LOG-1076: Opt-in cert generation in EO
  Makefile
  apis/logging/v1/elasticsearch_types.go
  controllers/logging/kibana_controller.go
  hack/cr.yaml
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  internal/constants/constants.go
  internal/k8shandler/certificates.go
  internal/k8shandler/configmaps_test.go
  internal/k8shandler/configuration_tmpl.go
  internal/k8shandler/kibana/kibana_test.go
  internal/k8shandler/kibana/reconciler.go
  internal/k8shandler/podtemplate.go
  internal/k8shandler/reconciler.go
  internal/k8shandler/secret.go
  test/e2e-olm/elasticsearch_metric_test.go
  test/e2e-olm/elasticsearch_test.go
  test/e2e-olm/elasticsearch_write_test.go
  test/e2e-olm/kibana_test.go
  test/e2e-olm/utils.go
Labels: approved, lgtm

#737 tidying up validateCASecret
  internal/k8shandler/certificates.go
Labels: approved, lgtm

#730 LOG-1458: Annotate with infrastructure features
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  internal/k8shandler/podtemplate.go
  manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, release/5.1

#731 LOG-1459: Annotate with infrastructure features
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, release/5.0

#736 Fix default logger in reconciliation loops
  go.mod
  go.sum
  main.go
  vendor/github.com/ViaQ/logerr/internal/kv/kv.go
  vendor/github.com/ViaQ/logerr/kverrors/kverrors.go
  vendor/github.com/ViaQ/logerr/log/logger.go
  vendor/modules.txt
Labels: approved, lgtm

#733 LOG-1421: Modify channels to PE recommendations
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#734 LOG-1463: Modify channels to PE recommendations
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#738 Fix storage class for e2e-upgrades running on GCP
  hack/testing-olm-upgrade/resources/cr.yaml
Labels: approved, lgtm

#739 Update access-control.md
  docs/access-control.md
Labels: approved, lgtm
