Repository openshift/elasticsearch-operator, pull requests merged in 2021-01, with the labels that each got.

#598 Bug 1913443: Rename prometheus filename for recording rules
  Dockerfile
  Makefile
  files/prometheus_recording_rules.yml
  internal/k8shandler/prometheus_rule.go
  internal/k8shandler/prometheus_rule_test.go
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, release/4.7

#516 fix broken link
  README.md
Labels: approved, bugzilla/valid-bug, lgtm, lifecycle/frozen, ok-to-test

#604 BUG 1913469: LOG-453 Expose recommendations based on cluster health
  docs/alerts.md
  files/prometheus_alerts.yml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#609 Bug 1913464: configure a warning level alert for when the CSV phase isn't success
  files/prometheus_alerts.yml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#610 Bug 1910259: Fix missing grafana dashboard in OCP 4.7
  controllers/logging/elasticsearch_controller.go
  internal/k8shandler/dashboards.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#608 [release-4.5] Bug 1909960: Allow kibana server to access OD tenantinfo
  pkg/k8shandler/configmaps_test.go
  pkg/k8shandler/configuration_tmpl.go
  pkg/k8shandler/confimaps_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#600 Bug 1908958: Change ElasticsearchClusterNotHealthy to 7 minutes
  files/prometheus_alerts.yml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#615 force make image to be a real target
  .gitignore
  .output/.keep
  Dockerfile.centos.patch
  Makefile
  docs/HACKING.md
Labels: approved, bugzilla/valid-bug, lgtm

#618 Bug 1893992: Improve elasticsearch indexmanagement rollover script
  internal/indexmanagement/scripts.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#623 Bug 1913469: fix link to the alert page
  files/prometheus_alerts.yml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#599 Bug 1890838: Condense indexmanagement into single cronjob
  internal/indexmanagement/reconcile.go
  internal/indexmanagement/reconcile_test.go
  internal/k8shandler/index_management.go
Labels: approved, backport/4.6, bugzilla/severity-high, bugzilla/valid-bug, lgtm, release/4.7

#575 [release-4.6] Bug 1885667: Updating index template logic to cap primary shards
  pkg/k8shandler/index_management.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#622 Bug 1908959: Change ElasticsearchClusterNotHealthy to 7 minutes
  files/prometheus_alerts.yml
  test/files/prometheus-unit-tests/test.yml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.6

#627 Bug 1916910: Condense indexmanagement into single cronjob
  pkg/indexmanagement/reconcile.go
  pkg/indexmanagement/reconcile_test.go
  pkg/k8shandler/index_management.go
  pkg/log/log.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.6

#590 [release-4.6] Bug 1902768: Restricting console links to clusterlogging operator use case
  pkg/k8shandler/kibana/kibana_test.go
  pkg/k8shandler/kibana/reconciler.go
  pkg/k8shandler/kibana/route.go
  test/e2e-olm/kibana_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#614 [release-4.6] Bug 1914987: Fix missing grafana dashboard upgrading to 4.7
  pkg/controller/elasticsearch/controller.go
  pkg/k8shandler/dashboards.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#631 LOG-1030: Adding degraded state to ES cluster status for prometheus case
  apis/logging/v1/elasticsearch_types.go
  internal/k8shandler/reconciler.go
  internal/k8shandler/status.go
  main.go
Labels: approved, bugzilla/valid-bug, lgtm

#632 Bug 1920215: LOG-1018: Updating IndexManagement to only create initial index template
  internal/constants/constants.go
  internal/elasticsearch/templates.go
  internal/k8shandler/index_management.go
  internal/k8shandler/index_management_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
