Repository openshift/elasticsearch-operator, pull requests merged in 2021-02, with the labels that each got.

#628 Bug 1918920: [LOGEXP 1009] Watch secret update for elasticsearch cluster
  controllers/logging/secret_controller.go
  internal/k8shandler/deployment.go
  internal/k8shandler/nodetypefactory.go
  internal/k8shandler/reconciler.go
  internal/k8shandler/statefulset.go
  main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#637 Update container registry to registry.ci.openshift.org
  Dockerfile
  Dockerfile.centos.patch
  hack/common
  hack/testing-olm-upgrade/upgrade-common
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, bugzilla/valid-bug, lgtm

#642 LOG-959: Adding degraded condition for when we are missing the required secret/fields for ES
  internal/constants/constants.go
  internal/k8shandler/reconciler.go
  internal/k8shandler/secret.go
Labels: approved, lgtm

#646 LOG-1041: Add icon in CSV
  bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
  config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
  controllers/logging/secret_controller.go
  internal/indexmanagement/reconcile.go
  internal/indexmanagement/reconcile_test.go
  internal/k8shandler/index_management_test.go
  manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Labels: approved, lgtm

#640 [release-4.6] Bug 1926276: watch route deletion in kibana controller:
  pkg/controller/kibana/controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#634 Bug 1923791: Updating IndexManagement to only create initial index template
  pkg/constants/constants.go
  pkg/elasticsearch/templates.go
  pkg/k8shandler/index_management.go
  pkg/k8shandler/index_management_test.go
  pkg/k8shandler/migrations/pvc_naming.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#649 LOG-1062: Removed 4.7 from manifests folder
  bundle.Dockerfile
  manifests/4.7/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
  manifests/4.7/image-references
  manifests/4.7/logging.openshift.io_elasticsearches_crd.yaml
  manifests/4.7/logging.openshift.io_kibanas_crd.yaml
  manifests/elasticsearch-operator.package.yaml
  olm_deploy/operatorregistry/Dockerfile
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/operator-install.sh
Labels: approved, lgtm

#652 Bug 1924657: Fix metrics ports exposed by operator deployment
  bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#643 LOG-1028: Rewrite e2e test in go
  hack/testing-olm/test-001-operator-sdk-e2e.sh
  hack/testing-olm/test-200-verify-es-metrics-access.sh
  hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
  test/e2e-olm/elasticsearch_metric_test.go
  test/e2e-olm/elasticsearch_write_test.go
  test/e2e-olm/main_test.go
  test/e2e-olm/utils.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, lgtm

#655 use image env vars instead of IMAGE_FORMAT
  Makefile
  hack/testing-olm-upgrade/upgrade-common
  olm_deploy/scripts/catalog-deploy.sh
  olm_deploy/scripts/registry-init.sh
Labels: approved, lgtm

#659 fix logging version to 5.1
  olm_deploy/scripts/catalog-deploy.sh
Labels: approved, lgtm
